### ISSUE TITLE
I am unable to use it with Netlify using Hugo 0.26

### ISSUE THREAD

**Issue by wasim-ullah** [digitalcraftsman/hugo-cactus-theme#41] opened 2017-09-11 00:59 UTC
Please guide me on this.

Is there a problem with theme version?

**Comment by digitalcraftsman** [comment] 2017-09-11 06:50
Hello @mrwullah,

the current version of the theme and Hugo 0.26 should work seamlessly. But without any context it's hard to tell where the issue is?

- could you give a more detailed description about the issue you're facing?
- did you followed the setup instructions in the README?
- what version of this theme are you using?
- could you share / link the build log of your site?

**Comment by wasim-ullah** [comment] 2017-09-11 07:03
Hi @digitalcraftsman 

Thanks for responding back to me.

When I am installing a web template created by nodejh called Cactus, it fails to install and gives an error "Production failed: Build script returned non-zero exit code: 255".

I have followed an in depth approach watching a tutorial: https://www.youtube.com/watch?v=CSwoCvd4QIc

I am using this version: https://themes.gohugo.io/hugo-theme-cactus-plus/

The web page I am updating on is https://wasim.netlify.com/

And this is where I have uploaded the theme: https://github.com/mrwullah/wasim/tree/master/themes/WasimUllah

Thank you once again! And I hope to get it resolved by you.

**Comment by digitalcraftsman** [comment] 2017-09-11 07:12
Well, you've to tell Hugo which theme should be used, either by running the build with `hugo -t WasimUllah` or by adding `theme = "WasimUllah"` to your config file :)

Please note that the hugo-theme-cactus-plus is a fork of this theme and not maintained by me. 

Cheers,
Digitalcraftsman

**Comment by wasim-ullah** [comment] 2017-09-11 07:16
Hey,

That doesn't work and gives the same error. Am I at wrong place to ask this question?

**Comment by digitalcraftsman** [comment] 2017-09-11 07:25
> That doesn't work and gives the same error. 

I've used `hugo server` first to preview your website and that worked fine. Hence the premature closing. At least does `hugo -t WasimUllah` generate the site with HTML. Now, we have to get the assets working (which is more a local issue for me since the paths aren't the same on my machine). I'll dig a bit deeper. 

> Am I at wrong place to ask this question?

Sort of. cactus-plus is a fork of this theme and I don't know what has been changed. Hence I would advise you to ask further questions there. But the ball is already rolling...

**Comment by digitalcraftsman** [comment] 2017-09-11 07:30
Could you trigger a rebuild with `theme = "WasimUllah"` set in the config file?

**Comment by wasim-ullah** [comment] 2017-09-11 07:34
I just used `theme ="WasimUllah"`

This is what comes after:

`12:32:05 PM: Build started12:32:05 PM: Fetching cached dependencies12:32:08 PM: No cached dependencies found. Cloning fresh repo12:32:08 PM: git lfs clone git@github.com:mrwullah/wasim12:32:11 PM: git remote rm origin12:32:11 PM: Preparing Git Reference refs/heads/master12:32:13 PM: Running build command: theme ="WasimUllah"12:32:16 PM: Downloading and installing node v6.11.3...12:32:16 PM: Downloading https://nodejs.org/dist/v6.11.3/node-v6.11.3-linux-x64.tar.xz...12:32:19 PM: 
                                                                           0.0%12:32:19 PM: 
#########################                                                 35.2%12:32:19 PM: 
#12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:19 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:20 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:21 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:22 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:23 PM: #12:32:24 PM: #12:32:24 PM: 12:32:24 PM: 112:32:24 PM: 012:32:24 PM: 012:32:24 PM: .12:32:24 PM: 012:32:24 PM: %12:32:24 PM: 12:32:24 PM: Computing checksum with sha256sum12:32:24 PM: Checksums matched!12:32:24 PM: Now using node v6.11.3 (npm v3.10.10)12:32:24 PM: Using version v6.11.3 of node12:32:24 PM: Using /opt/buildhome/.rvm/gems/ruby-2.1.212:32:25 PM: /opt/build/build.sh: line 427: theme: command not found12:32:25 PM: Build complete: exit code: 12712:32:25 PM: Cleaning up docker container12:32:25 PM: Error running command: Build script returned non-zero exit code: 12712:32:26 PM: An error occurred while building the site, skipping the deploy and cache refresh.12:32:26 PM: Build script returned non-zero exit code: 12712:32:27 PM: Finished processing build request in 21.612757816s`

It looks like the issue is again the same.

**Comment by digitalcraftsman** [comment] 2017-09-11 07:39
Why is your build command `theme ="WasimUllah"`? 
Add `theme ="WasimUllah"` as a new line to your config file if this isn't already the case and use just `hugo` as build command.

**Comment by wasim-ullah** [comment] 2017-09-11 07:46
> Why is your build command theme ="WasimUllah"?
Because I was told to use it. :)

This is where I added `theme ="WasimUllah` : https://github.com/mrwullah/wasim/blob/master/config.toml

I have used hugo as build command, and the new error is: "Production failed: Build script returned non-zero exit code: 255: Today at 12:43 pm"

This is the detailed version of it:

`12:43:44 PM: Build started12:43:45 PM: Fetching cached dependencies12:43:45 PM: No cached dependencies found. Cloning fresh repo12:43:45 PM: git lfs clone git@github.com:mrwullah/wasim12:43:47 PM: git remote rm origin12:43:47 PM: Preparing Git Reference refs/heads/master12:43:48 PM: Running build command: hugo12:43:50 PM: Downloading and installing node v6.11.3...12:43:50 PM: Downloading https://nodejs.org/dist/v6.11.3/node-v6.11.3-linux-x64.tar.xz...12:43:50 PM: 12:43:50 PM:   0.0%12:43:50 PM: 12:43:50 PM:   1.1%12:43:51 PM: 
###12:43:51 PM: 12:43:51 PM: 12:43:51 PM:   4.12:43:51 PM: 7%12:43:51 PM: 
############                                                              16.8%12:43:51 PM: 
########################                                                  34.7%12:43:51 PM: 
#################################################12:43:51 PM:      68.5%12:43:51 PM: 
######################################################################    98.6%12:43:51 PM: 
########################################################################12:43:51 PM: 100.0%12:43:51 PM: Computing checksum with sha256sum12:43:51 PM: Checksums matched!12:43:53 PM: Now using node v6.11.3 (npm v3.10.10)12:43:53 PM: Using version v6.11.3 of node12:43:53 PM: Using /opt/buildhome/.rvm/gems/ruby-2.1.212:43:53 PM: ERROR: 2017/09/11 07:43:53 hugo.go:421: Current theme does not support Hugo version 0.17. Minimum version required is 0.1812:43:53 PM: Started building sites ...12:43:53 PM: ERROR: 2017/09/11 07:43:53 template.go:477: template: theme/partials/footer.html:9: function "now" not defined12:43:53 PM: ERROR: 2017/09/11 07:43:53 template.go:132: template: "theme/partials/footer.html" is an incomplete or empty template; defined templates are: "theme/partials/social.html", "_internal/shortcodes/gist.html", "_internal/shortcodes/tweet.html", "_internal/_default/robots.txt", "theme/_default/single.html", "theme/partials/github-issues-tip.html", "theme/partials/pagination.html", "theme/partials/duoshuo.html", "theme/partials/latest-posts.html", "_internal/shortcodes/ref.html", "_internal/shortcodes/vimeo.html", "_internal/_default/sitemap.xml", "_internal/google_news.html", "_internal/google_analytics_async.html", "theme/index.html", "theme/partials/tagcloud.html", "theme/partials/profile.html", "_internal/_default/rss.xml", "_internal/_default/sitemapindex.xml", "_internal/pagination.html", "theme/_default/list.html", "theme/partials/js.html", "theme/partials/nav.html", "theme/section/about.html", "theme/taxonomy/tag.terms.html", "_internal/shortcodes/test.html", "_internal/shortcodes/figure.html", "_internal/shortcodes/youtube.html", "_internal/schema.html", "_internal/google_analytics.html", "theme/partials/disqus.html", "_internal/shortcodes/speakerdeck.html", "_internal/opengraph.html", "theme/partials/post-list.html", "theme/partials/share.html", "_internal/shortcodes/relref.html", "_internal/shortcodes/highlight.html", "_internal/disqus.html", "_internal/twitter_cards.html", "theme/404.html", "theme/partials/head.html" in theme/partials/footer.html12:43:53 PM: ERROR: 2017/09/11 07:43:53 template.go:132: template: "theme/partials/footer.html" is an incomplete or empty template; defined templates are: "_internal/_default/rss.xml", "_internal/_default/sitemapindex.xml", "_internal/pagination.html", "theme/_default/list.html", "theme/partials/js.html", "theme/partials/nav.html", "theme/section/about.html", "theme/taxonomy/tag.terms.html", "_internal/shortcodes/test.html", "_internal/shortcodes/figure.html", "_internal/shortcodes/youtube.html", "_internal/schema.html", "_internal/google_analytics.html", "theme/partials/disqus.html", "_internal/shortcodes/speakerdeck.html", "_internal/opengraph.html", "theme/partials/post-list.html", "theme/partials/share.html", "_internal/shortcodes/relref.html", "_internal/shortcodes/highlight.html", "_internal/disqus.html", "_internal/twitter_cards.html", "theme/404.html", "theme/partials/head.html", "_internal/shortcodes/gist.html", "_internal/shortcodes/tweet.html", "_internal/_default/robots.txt", "theme/_default/single.html", "theme/partials/github-issues-tip.html", "theme/partials/pagination.html", "theme/partials/social.html", "_internal/shortcodes/ref.html", "_internal/shortcodes/vimeo.html", "_internal/_default/sitemap.xml", "_internal/google_news.html", "_internal/google_analytics_async.html", "theme/index.html", "theme/partials/duoshuo.html", "theme/partials/latest-posts.html", "theme/partials/tagcloud.html", "theme/partials/profile.html" in theme/partials/footer.html12:43:54 PM: ERROR: 2017/09/11 07:43:53 template.go:132: template: "theme/partials/footer.html" is an incomplete or empty template; defined templates are: "_internal/shortcodes/youtube.html", "_internal/schema.html", "_internal/google_analytics.html", "theme/partials/disqus.html", "_internal/shortcodes/test.html", "_internal/shortcodes/figure.html", "theme/partials/post-list.html", "theme/partials/share.html", "_internal/shortcodes/speakerdeck.html", "_internal/opengraph.html", "_internal/disqus.html", "_internal/twitter_cards.html", "theme/404.html", "theme/partials/head.html", "_internal/shortcodes/relref.html", "_internal/shortcodes/highlight.html", "_internal/_default/robots.txt", "theme/_default/single.html", "theme/partials/github-issues-tip.html", "theme/partials/pagination.html", "theme/partials/social.html", "_internal/shortcodes/gist.html", "_internal/shortcodes/tweet.html", "_internal/_default/sitemap.xml", "_internal/google_news.html", "_internal/google_analytics_async.html", "theme/index.html", "theme/partials/duoshuo.html", "theme/partials/latest-posts.html", "_internal/shortcodes/ref.html", "_internal/shortcodes/vimeo.html", "theme/partials/tagcloud.html", "theme/partials/profile.html", "_internal/pagination.html", "theme/_default/list.html", "_internal/_default/rss.xml", "_internal/_default/sitemapindex.xml", "theme/section/about.html", "theme/taxonomy/tag.terms.html", "theme/partials/js.html", "theme/partials/nav.html" in theme/partials/footer.html12:43:54 PM: ERROR: 2017/09/11 07:43:53 template.go:132: template: "theme/partials/footer.html" is an incomplete or empty template; defined templates are: "_internal/twitter_cards.html", "theme/404.html", "theme/partials/head.html", "_internal/shortcodes/relref.html", "_internal/shortcodes/highlight.html", "_internal/disqus.html", "theme/_default/single.html", "theme/partials/github-issues-tip.html", "theme/partials/pagination.html", "theme/partials/social.html", "_internal/shortcodes/gist.html", "_internal/shortcodes/tweet.html", "_internal/_default/robots.txt", "_internal/google_news.html", "_internal/google_analytics_async.html", "theme/index.html", "theme/partials/duoshuo.html", "theme/partials/latest-posts.html", "_internal/shortcodes/ref.html", "_internal/shortcodes/vimeo.html", "_internal/_default/sitemap.xml", "theme/partials/tagcloud.html", "theme/partials/profile.html", "theme/_default/list.html", "_internal/_default/rss.xml", "_internal/_default/sitemapindex.xml", "_internal/pagination.html", "theme/taxonomy/tag.terms.html", "theme/partials/js.html", "theme/partials/nav.html", "theme/section/about.html", "_internal/schema.html", "_internal/google_analytics.html", "theme/partials/disqus.html", "_internal/shortcodes/test.html", "_internal/shortcodes/figure.html", "_internal/shortcodes/youtube.html", "theme/partials/share.html", "_internal/shortcodes/speakerdeck.html", "_internal/opengraph.html", "theme/partials/post-list.html" in theme/partials/footer.html12:43:54 PM: ERROR: 2017/09/11 07:43:53 template.go:132: template: "theme/partials/footer.html" is an incomplete or empty template; defined templates are: "_internal/schema.html", "_internal/google_analytics.html", "theme/partials/disqus.html", "_internal/shortcodes/test.html", "_internal/shortcodes/figure.html", "_internal/shortcodes/youtube.html", "theme/partials/share.html", "_internal/shortcodes/speakerdeck.html", "_internal/opengraph.html", "theme/partials/post-list.html", "_internal/twitter_cards.html", "theme/404.html", "theme/partials/head.html", "_internal/shortcodes/relref.html", "_internal/shortcodes/highlight.html", "_internal/disqus.html", "theme/_default/single.html", "theme/partials/github-issues-tip.html", "theme/partials/pagination.html", "theme/partials/social.html", "_internal/shortcodes/gist.html", "_internal/shortcodes/tweet.html", "_internal/_default/robots.txt", "_internal/google_news.html", "_internal/google_analytics_async.html", "theme/index.html", "theme/partials/duoshuo.html", "theme/partials/latest-posts.html", "_internal/shortcodes/ref.html", "_internal/shortcodes/vimeo.html", "_internal/_default/sitemap.xml", "theme/partials/tagcloud.html", "theme/partials/profile.html", "theme/_default/list.html", "_internal/_default/rss.xml", "_internal/_default/sitemapindex.xml", "_internal/pagination.html", "theme/taxonomy/tag.terms.html", "theme/partials/js.html", "theme/partials/nav.html", "theme/section/about.html" in theme/partials/footer.html12:43:54 PM: Build complete: exit code: 25512:43:54 PM: ERROR: 2017/09/11 07:43:53 template.go:132: template: "theme/partials/footer.html" is an incomplete or empty template; defined templates are: "_internal/twitter_cards.html", "theme/404.html", "theme/partials/head.html", "_internal/shortcodes/relref.html", "_internal/shortcodes/highlight.html", "_internal/disqus.html", "theme/_default/single.html", "theme/partials/github-issues-tip.html", "theme/partials/pagination.html", "theme/partials/social.html", "_internal/shortcodes/gist.html", "_internal/shortcodes/tweet.html", "_internal/_default/robots.txt", "_internal/google_news.html", "_internal/google_analytics_async.html", "theme/index.html", "theme/partials/duoshuo.html", "theme/partials/latest-posts.html", "_internal/shortcodes/ref.html", "_internal/shortcodes/vimeo.html", "_internal/_default/sitemap.xml", "theme/partials/tagcloud.html", "theme/partials/profile.html", "theme/_default/list.html", "_internal/_default/rss.xml", "_internal/_default/sitemapindex.xml", "_internal/pagination.html", "theme/taxonomy/tag.terms.html", "theme/partials/js.html", "theme/partials/nav.html", "theme/section/about.html", "_internal/schema.html", "_internal/google_analytics.html", "theme/partials/disqus.html", "_internal/shortcodes/test.html", "_internal/shortcodes/figure.html", "_internal/shortcodes/youtube.html", "theme/partials/share.html", "_internal/shortcodes/speakerdeck.html", "_internal/opengraph.html", "theme/partials/post-list.html" in theme/partials/footer.html12:43:54 PM: Cleaning up docker container12:43:54 PM: ERROR: 2017/09/11 07:43:53 template.go:132: template: "theme/partials/footer.html" is an incomplete or empty template; defined templates are: "theme/taxonomy/tag.terms.html", "theme/partials/js.html", "theme/partials/nav.html", "theme/section/about.html", "_internal/schema.html", "_internal/google_analytics.html", "theme/partials/disqus.html", "_internal/shortcodes/test.html", "_internal/shortcodes/figure.html", "_internal/shortcodes/youtube.html", "theme/partials/share.html", "_internal/shortcodes/speakerdeck.html", "_internal/opengraph.html", "theme/partials/post-list.html", "_internal/twitter_cards.html", "theme/404.html", "theme/partials/head.html", "_internal/shortcodes/relref.html", "_internal/shortcodes/highlight.html", "_internal/disqus.html", "theme/_default/single.html", "theme/partials/github-issues-tip.html", "theme/partials/pagination.html", "theme/partials/social.html", "_internal/shortcodes/gist.html", "_internal/shortcodes/tweet.html", "_internal/_default/robots.txt", "_internal/google_news.html", "_internal/google_analytics_async.html", "theme/index.html", "theme/partials/duoshuo.html", "theme/partials/latest-posts.html", "_internal/shortcodes/ref.html", "_internal/shortcodes/vimeo.html", "_internal/_default/sitemap.xml", "theme/partials/tagcloud.html", "theme/partials/profile.html", "theme/_default/list.html", "_internal/_default/rss.xml", "_internal/_default/sitemapindex.xml", "_internal/pagination.html" in theme/partials/footer.html12:43:54 PM: Error running command: Build script returned non-zero exit code: 25512:43:54 PM: Built site for language en:0 draft content0 future content0 expired content2 pages created0 non-page files copied1 paginator pages created12:43:54 PM: 0 tags created0 categories createdtotal in 17 ms12:43:54 PM: An error occurred while building the site, skipping the deploy and cache refresh.12:43:54 PM: Build script returned non-zero exit code: 25512:43:55 PM: Finished processing build request in 10.212510836s`

Thank you!

**Comment by digitalcraftsman** [comment] 2017-09-11 07:50
My next guess would be this line:

> Current theme does not support Hugo version 0.17. Minimum version required is 0.18

Where did you specify that Hugo 0.17 should be used? Try to use v0.18 or newer.

**Comment by wasim-ullah** [comment] 2017-09-11 07:55
Here (https://themes.gohugo.io/hugo-theme-cactus-plus/) it says:

> Minimum Hugo Version: 0.18

And I used this (v0.27) version: https://github.com/gohugoio/hugo/releases/tag/v0.27

> Where did you specify that Hugo 0.17 should be used? Try to use v0.18 or newer.
Where do I need to specify that please?

Hope that I was on the right track.

**Comment by digitalcraftsman** [comment] 2017-09-11 08:00
Netlify allows you to build your website with a few dozen versions of Hugo. But you've to specify which one should be used. Please have a look at [this blog post](https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/) and add the environment variable accordingly.

0.17 seems like the default version that's used to build sites unless you explicitly set a different one.

**Comment by wasim-ullah** [comment] 2017-09-11 09:03
Hey, I have:

> You can also do this in the configuration file directly. Replace the previous section with a new production section:

```
[context.production.environment]
  HUGO_VERSION = "0.20"
```

And that's here: https://github.com/mrwullah/wasim/blob/master/config.toml

The issue is: "Build script returned non-zero exit code: 255"

PS: I wonder if I could ask you to do this on my behalf (using my Netlify login credentials too that I can email to you).

**Comment by digitalcraftsman** [comment] 2017-09-11 11:10
Can't you add me as a collaborator to your website?

**Comment by wasim-ullah** [comment] 2017-09-11 11:13
@digitalcraftsman : happily! what's the suitable email address?
Somebody at Netlify tells me that it's more of Hugo issue, now I think that you're the right helper for me.

**Comment by digitalcraftsman** [comment] 2017-09-11 19:02
I've send you an email to your Gmail address.

**Comment by wasim-ullah** [comment] 2017-09-12 06:30
Thanks a ton.

**Closed as completed** 2017-09-12 07:11 UTC
